### 查询课程信息
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus":""
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 新增课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "fdsf",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "tagstagstags",
  "grade": "204001",
  "description": "java网络编程高级java网络编程高级java网络编程高级"
}


### 课程查询
GET {{content_host}}/content/course/40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MjUxOTA1MDksImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjAzOGUyMDM3LThhNjQtNDcxOS04ODBkLTEwNzA5NDE2MTlkYyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.TFNEf95qUiKYTfGgF6r0aGrBKs0tt0d5RLYvCHZ8Beo


### 课程计划查询
GET {{content_host}}/content/teachplan/117/tree-nodes


### 课程查询
GET {{gateway_host}}/content/course/40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcyNTMxNjk0MywiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI4OTQxZTgzMi02MDQxLTQ1MDktOWUyMy0yNWI2NWMwNDY0ZGIiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.OwwSasuwtO5wSI74DUKx2BcFJek7ceUc1vxKNOZaMTA
