### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="0.jpg"
Content-Type: application/octet-stream

< C:/Users/chaic/OneDrive/图片/屏幕快照/0.jpg